[package]
name = "fta-wasm"
version = "0.1.10"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fta = { path = "../fta" }
serde_json = "1.0.96"
wasm-bindgen = "0.2.85"