[package]
name = "fta"
version = "0.1.11"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Fast TypeScript Analyzer"
homepage = "https://ftaproject.dev"
documentation = "https://github.com/sgb-io/fta"
repository = "https://github.com/sgb-io/fta"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
env_logger = "0.9"
globset = "0.4"
ignore = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swc_common = "0.31.12"
swc_ecma_ast = "0.104.5"
swc_ecma_parser = "0.134.12"
swc_ecma_visit = "0.90.5"
tempfile = "3.2.0"