name: Publish NPM Package (Dry Run)

on: workflow_call

jobs:
  publish_fta_cli_dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download macOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-binaries
          path: artifact/

      - name: Download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-binaries
          path: artifact/

      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-binaries
          path: artifact/

      - name: Extract nix artifacts
        run: |
          for file in artifact/*.tar.gz; do
            base=$(basename -- "$file")
            dirname="${base%%.*}"
            mkdir -p packages/fta/binaries/"$dirname"
            tar -xzf "$file" -C packages/fta/binaries/"$dirname"
          done

      - name: Extract artifacts
        run: |
          for file in artifact/*.zip; do
            dir=$(basename "$file" .zip)
            mkdir -p "packages/fta/binaries/$dir"
            unzip -o "$file" -d "packages/fta/binaries/$dir"
          done

          # List out the binaries dir
          ls -R packages/fta/binaries/

      - name: Install Verdaccio
        run: npm install -g verdaccio verdaccio-memory verdaccio-auth-memory

      - name: Setup Verdaccio Config
        run: |
          mkdir -p $HOME/.config/verdaccio
          cp .github/verdaccio-config.yml $HOME/.config/verdaccio/config.yml

      - name: Start Verdaccio
        run: |
          npx verdaccio --config $HOME/.config/verdaccio/config.yml --listen 4873 &
          sleep 10

      - name: Publish package
        env:
          NPM_CONFIG_REGISTRY: "http://localhost:4873/"
          NPM_CONFIG_USERNAME: "test"
          NPM_CONFIG_PASSWORD: "test"
          NPM_CONFIG_EMAIL: "test@test.com"
        run: |
          cd packages/fta
          npm publish --registry http://localhost:4873
          cd ../

      - name: Install and check package
        run: |
          npm install fta-cli --registry http://localhost:4873
          # Execute fta via the npm package
          fta-cli .github
